### ISSUE TITLE
IE8兼容调整

### ISSUE THREAD

**Issue by JsonRuby** [h01/bmenu#1]
IE8 目前还是很多人在用的.IE7就算了.
因为WIN7 默认就是IE8.可能以后不用care IE8.目前还是不行.

我做了一点点的改动如下,LZ请参考

1.//IE8不支持ByClassName.用jquery或者其他替代方案
 hide: function () {
        // 隐藏所有菜单
        // var _mns = document.getElementsByClassName("dropdown-menu multi-level bmenu");
        var _mns = $(".bmenu"); 

2.IE8的定位问题.IE8是没有e.pageX的
  if (e.pageY) {
                menu.style.top = e.pageY + "px";
                menu.style.left = e.pageX + "px";
            } else {
                menu.style.top = e.clientY + "px";
                menu.style.left = e.clientX + "px";
            }

3.IE8 class好像是敏感词..加上引号
 var _menu = this.createObj('ul', {
            "class": 'dropdown-menu multi-level bmenu',

4.IE8 obj click 事件也是没有e.button的
 obj.onclick = function (e) {
            if (e == undefined || e.button == 0) {
                bmenu.hide();
            };
        };

**Comment by h01** [comment]
嗯，一般针对IE9一下（或者说IE系列的）我都没有也不会去考虑的。。因为只是用来完成个人的小东西而已，还有这个东西很久没更新了，以后打算重新写的，不过还是谢谢你的反馈
